### ISSUE TITLE
OMG WHAT JUST HAPPENED - CatChat DELETED?

### ISSUE THREAD

**Issue by AfterNetwork** [MikeDev101/catchatmmo#1]
What the?

**Comment by MikeDev101** [comment]
To clear out the obsolete and unnecessary files/folders. I will bring it back online.

**Comment by AfterNetwork** [comment]
Okay.

**Comment by AfterNetwork** [comment]
Wait. that reset the contributors. re-invite me

**Comment by MikeDev101** [comment]
Done

**Comment by AfterNetwork** [comment]
I'm going to upload the 7-Zip downloader.

**Comment by MikeDev101** [comment]
Just link it, please... We don't need any more bloat in the repository like we did last time... ;-;
