### ISSUE TITLE
cannot dowload catchat

### ISSUE THREAD

**Issue by TechMobz** [MikeDev101/catchatmmo#2]
please help. I have tried to get it, and I know I have the right os and stuff, but I can't open it.

**Comment by MikeDev101** [comment]
Hi, the file that the game is compressed into is a 7Zip file. Please use 7Zip to extract the files.

**Comment by TechMobz** [comment]
Hi. Ok

**Comment by TechMobz** [comment]
Thanks! I know have it up, and it's looking good!
