### ISSUE TITLE
Out of date source code

### ISSUE THREAD

**Issue by MikeDev101** [MikeDev101/catchatmmo#5]
The code that is inside of the CatChat source code folder is out of date. From now on, please do NOT upload folders into the repository. Instead, please use .zip or .7z files instead of uploading folders, as they are hard to manage and clear out when an update or change is made to the master branch. ;-;

**Comment by AfterNetwork** [comment]
I can just label them by Alpha-1.1, Alpha-1.2.
I'm going to close this unless MikeDEV comes up with a response.
